### ISSUE TITLE
[Arch Linux] Build script fails with multiple demoextend references

### ISSUE THREAD

**Issue by hfc2x** [chocolate-doom/chocpkg#22]
Hello.

I'm following [the instructions from the wiki](https://www.chocolate-doom.org/wiki/index.php/Building_Chocolate_Doom_on_Linux_(generic)) to build the port from source, and I made sure I have all the packages and dependencies mentioned. However, the build always fails with the following output:
```
/usr/bin/ld: hexen/libhexen.a(g_game.o):/home/[user]/chocpkg/build/chocolate-doom-3.0.1/src/hexen/g_game.c:101: multiple definition of `demoextend'; hexen/libhexen.a(mn_menu.o):/home/[user]/chocpkg/build/chocolate-doom-3.0.1/src/hexen/mn_menu.c:134: first defined here
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:880: chocolate-hexen] Error 1
make[3]: Leaving directory '/home/[user]/chocpkg/build/chocolate-doom-3.0.1/src'
make[2]: *** [Makefile:1088: all-recursive] Error 1
make[2]: Leaving directory '/home/[user]/chocpkg/build/chocolate-doom-3.0.1/src'
make[1]: *** [Makefile:585: all-recursive] Error 1
make[1]: Leaving directory '/home/[user]/chocpkg/build/chocolate-doom-3.0.1'
make: *** [Makefile:438: all] Error 2
```
Are there instructions missing, or is it just that the multiple references to `demoextend` are causing the build process to fail? I'm running Manjaro Linux with the 5.15.55-1 kernel.

**Comment by fragglet** [comment]
Try the latest version from Git, I believe this has been fixed.

**Comment by fabiangreffrath** [comment]
This is the relevant commit, in case you'd prefer to backport it:
https://github.com/chocolate-doom/chocolate-doom/commit/a8fd4b1f563d24d4296c3e8225c8404e2724d4c2

**Comment by hfc2x** [comment]
Nice, it works. Thanks!
