### ISSUE TITLE
add autoconf to packages / build failure on a clean-ish OS X system

### ISSUE THREAD

**Issue by jmtd** [chocolate-doom/chocpkg#4]
Happened to try `chocpkg` on a recently re-installed El Capitan last night, and hit the following

```
$ ./chocpkg build chocolate-doom
..lding chocolate-doom...
=======================================================

/Users/jon/chocpkg/chocpkg/modules/build_autotools.sh: line 29:
autoreconf: command not found
```

I started by `git clone`ing the repository, which prompted me to intall the XCode command-line tools, which completed successfully (as evidenced by the `git clone` working :)) so autoconf is not installed system-wide as part of that process.

I guess a solution would be to add autoconf to the list of dependencies that `chocpkg` can download and build.

**Comment by fragglet** [comment]
Yeah, I forgot that I manually installed autotools on my system.

We can probably add packages for automake/autoconf/etc. but it's probably a good idea to explicitly define what packages are "essential" dependencies (ie. chocpkg needs them and won't work without them). For example I'd consider gcc and git essential dependencies.

**Comment by fragglet** [comment]
Pushed a couple of commits which add packages for autotools. I opened #6 for clarifying base dependencies.
