### ISSUE TITLE
libpng missing from server and wrong checksum (for 1.6.10)

### ISSUE THREAD

**Issue by fx02** [chocolate-doom/chocpkg#9]
Link: http://www.doom.com.hr/cndoom/support/libraries/libpng-1.6.17.tar.gz
Checksum: a18233c99e1dc59a256180e6871d9305a42e91b3f98799b3ceb98e87e9ec5e31

**Comment by fragglet** [comment]
Currently using a copy from chocolate-doom.org, so this shouldn't be an issue.
